project_id = "ljtikbkilyeyuexzhaqd"

[functions.connect-google]
verify_jwt = false

[functions.oauth-google-callback]
verify_jwt = false

[functions.payment-monitor]
verify_jwt = true

[functions.google-drive-enhanced]
verify_jwt = true