import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';

export interface ScenarioSuggestion {
  type: 'opportunity' | 'reminder' | 'seasonal';
  title: string;
  description: string;
  scenarioTitle: string;
  scenarioId?: string;
  category: string;
  icon: 'signal' | 'clock' | 'calendar';
  triggerLabel?: string;
  autoGenerated?: boolean;
}

export function useSmartScenarios() {
  const [suggestions, setSuggestions] = useState<ScenarioSuggestion[]>([]);
  const [loading, setLoading] = useState(true);

  const generate = useCallback(async () => {
    try {
      const { data: userData } = await supabase.auth.getUser();
      if (!userData?.user?.id) return;
      const userId = userData.user.id;
      const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();

      const [leadRes, topicsRes, practiceRes, scenariosRes, triggerScenariosRes] = await Promise.all([
        supabase
          .from('lead_signals')
          .select('comment_text, commenter_name, platform, post_id')
          .eq('status', 'new')
          .order('created_at', { ascending: false })
          .limit(10),

        supabase
          .from('content_posts')
          .select('topic_keywords, content_anchor, demand_moment_type')
          .eq('user_id', userId)
          .order('created_at', { ascending: false })
          .limit(20),

        supabase
          .from('voice_practice_sessions')
          .select('id', { count: 'exact', head: true })
          .eq('user_id', userId)
          .gte('created_at', sevenDaysAgo),

        supabase
          .from('training_scenarios')
          .select('id, title, description, category, tags')
          .eq('status', 'published')
          .limit(50),

        // Fetch auto-generated scenarios from triggers
        supabase
          .from('scenarios')
          .select('id, title, scenario_text, category, difficulty, auto_generated, trigger_id')
          .eq('is_active', true)
          .eq('auto_generated', true)
          .order('created_at', { ascending: false })
          .limit(10),
      ]);

      const results: ScenarioSuggestion[] = [];
      const scenarios = scenariosRes.data ?? [];
      const triggerScenarios = triggerScenariosRes.data ?? [];
      const practiceCount = practiceRes.count ?? 0;

      // PRIORITY 1: Auto-generated trigger scenarios
      for (const ts of triggerScenarios.slice(0, 2)) {
        let triggerLabel = 'Based on real activity';
        if (ts.trigger_id) {
          const { data: trigger } = await supabase
            .from('scenario_triggers')
            .select('trigger_type')
            .eq('id', ts.trigger_id)
            .single();
          if (trigger) {
            triggerLabel = trigger.trigger_type === 'conversation'
              ? 'Based on real client interaction'
              : trigger.trigger_type === 'mistake'
                ? 'Missed opportunity'
                : 'New policy scenario';
          }
        }

        results.push({
          type: 'opportunity',
          title: triggerLabel,
          description: ts.scenario_text?.slice(0, 120) + '...' || ts.title,
          scenarioTitle: ts.title,
          scenarioId: ts.id,
          category: ts.category,
          icon: 'signal',
          triggerLabel,
          autoGenerated: true,
        });
      }

      // PRIORITY 2: Engagement signal matches
      const usedIds = new Set(results.map((r) => r.scenarioId));
      const leads = leadRes.data ?? [];
      const commentKeywords = extractKeywords(leads.map((l) => l.comment_text ?? '').join(' '));
      const signalMatches = matchScenariosToKeywords(scenarios, commentKeywords);
      if (signalMatches.length > 0 && !usedIds.has(signalMatches[0].id)) {
        const match = signalMatches[0];
        results.push({
          type: 'opportunity',
          title: 'Families are asking about this topic',
          description: `Recent engagement signals relate to ${match.category?.toLowerCase() || 'care conversations'}.`,
          scenarioTitle: match.title,
          scenarioId: match.id,
          category: match.category,
          icon: 'signal',
        });
      }

      // PRIORITY 3: Content topic matches
      const posts = topicsRes.data ?? [];
      const topicKeywords = extractKeywords(
        posts.flatMap((p) => [...(p.topic_keywords ?? []), p.content_anchor ?? '', p.demand_moment_type ?? '']).join(' ')
      );
      const topicMatches = matchScenariosToKeywords(scenarios, topicKeywords);
      const uniqueTopicMatch = topicMatches.find((m) => !usedIds.has(m.id));
      if (uniqueTopicMatch && results.length < 3) {
        results.push({
          type: 'opportunity',
          title: 'Practice what you post about',
          description: `Your recent content covers ${uniqueTopicMatch.category?.toLowerCase() || 'caregiving topics'}.`,
          scenarioTitle: uniqueTopicMatch.title,
          scenarioId: uniqueTopicMatch.id,
          category: uniqueTopicMatch.category,
          icon: 'signal',
        });
      }

      // PRIORITY 4: Seasonal
      const month = new Date().getMonth();
      const seasonalCategories = getSeasonalCategories(month);
      const seasonalMatch = scenarios.find(
        (s) =>
          !new Set(results.map((r) => r.scenarioId)).has(s.id) &&
          seasonalCategories.some(
            (kw) =>
              s.title?.toLowerCase().includes(kw) ||
              s.category?.toLowerCase().includes(kw) ||
              s.tags?.some((t: string) => t.toLowerCase().includes(kw))
          )
      );
      if (seasonalMatch && results.length < 3) {
        results.push({
          type: 'seasonal',
          title: 'Seasonal conversation prep',
          description: `This time of year, families often reach out about ${seasonalCategories[0]} concerns.`,
          scenarioTitle: seasonalMatch.title,
          scenarioId: seasonalMatch.id,
          category: seasonalMatch.category,
          icon: 'calendar',
        });
      }

      // PRIORITY 5: Inactivity reminder
      if (practiceCount === 0 && results.length < 3) {
        const fallback = scenarios.find((s) => !new Set(results.map((r) => r.scenarioId)).has(s.id));
        results.push({
          type: 'reminder',
          title: "You haven't practiced this week",
          description: 'Regular practice improves how your team handles real calls.',
          scenarioTitle: fallback?.title ?? 'Intake Call Practice',
          scenarioId: fallback?.id,
          category: fallback?.category ?? 'Intake Calls',
          icon: 'clock',
        });
      }

      setSuggestions(results.slice(0, 3));
    } catch (err) {
      console.error('Smart scenario error:', err);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { generate(); }, [generate]);

  return { suggestions, loading };
}

/* ---- Helpers ---- */

const CARE_KEYWORDS = [
  'hospital', 'discharge', 'dementia', 'memory', 'cost', 'price', 'afford',
  'burnout', 'caregiver', 'respite', 'safety', 'trust', 'intake', 'loneliness',
  'companion', 'hospice', 'surgery', 'recovery', 'fall', 'medication',
];

function extractKeywords(text: string): string[] {
  const lower = text.toLowerCase();
  return CARE_KEYWORDS.filter((kw) => lower.includes(kw));
}

function matchScenariosToKeywords(scenarios: any[], keywords: string[]): any[] {
  if (keywords.length === 0) return [];
  return scenarios
    .map((s) => {
      const blob = [s.title, s.description, s.category, ...(s.tags ?? [])].join(' ').toLowerCase();
      const score = keywords.filter((kw) => blob.includes(kw)).length;
      return { ...s, score };
    })
    .filter((s) => s.score > 0)
    .sort((a, b) => b.score - a.score);
}

function getSeasonalCategories(month: number): string[] {
  if (month === 10 || month === 11) return ['loneliness', 'holiday', 'companion'];
  if (month === 0 || month === 1) return ['hospital', 'discharge', 'recovery'];
  if (month >= 2 && month <= 4) return ['caregiver', 'burnout', 'respite'];
  if (month >= 5 && month <= 7) return ['safety', 'fall', 'dementia'];
  return ['intake', 'cost', 'trust'];
}
