// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljtikbkilyeyuexzhaqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqdGlrYmtpbHlleXVleHpoYXFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTYyOTEsImV4cCI6MjA2Mzc3MjI5MX0.sAsOSuzaNTq3ii_rkBvH4Q7X8wn2weny0E5VjI-mrys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});